spring:
  application:
    name: weather-api
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=60s
  mvc:
    problem-details:
      enabled: true

weather:
  open-meteo:
    url: "https://api.open-meteo.com/v1/forecast"
    timeout-ms: 1000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

